[package]
name = "traversable-error"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[lib]

[dependencies]
anyhow = { workspace = true}
traversable-derive = { workspace = true}

[lints]
workspace = true
