[package]
name = "uv-performance-flate2-backend"
version = "0.1.0"
publish = false
edition = "2021"

[lib]
doctest = false

# Use `zlib-ng` on all supported platforms.
[target.'cfg(not(any(target_arch = "s390x", target_os = "freebsd")))'.dependencies]
flate2 = { version = "1.0.28", default-features = false, features = ["zlib-ng"] }

# Use `zlib-rs` everywhere else.
[target.'cfg(any(target_arch = "s390x", target_os = "freebsd"))'.dependencies]
flate2 = { version = "1.0.28", default-features = false, features = ["zlib-rs"] }
