[project]
name = "pdm-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Charlie Marsh", email = "charlie.r.marsh@gmail.com" }
]
requires-python = ">=3.13.0"
dependencies = []

[project.optional-dependencies]
all = [
    "pdm-example[fastapi_optional]",
]
fastapi_optional = [
    "fastapi>=0.110.2",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.uv.workspace]
members = ["poetry-example"]
