[profile.default]
# Mark tests that take longer than 10s as slow.
# Terminate after 10 minutes as a stop-gap measure to terminate on deadlock.
slow-timeout =  { period = "10s", terminate-after = 60 }
