name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUSTUP_MAX_RETRIES: 10
  PYTHON_VERSION: "3.12"

jobs:
  cargo-test-linux:
    name: "cargo test | ubuntu"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: rui314/setup-mold@v1

      - uses: Swatinem/rust-cache@v2

      - name: "Install Rust toolchain"
        run: rustup show

      - uses: astral-sh/setup-uv@v5
      - name: "Install required Python versions"
        run: uv python install

      - name: "Cargo build"
        run: cargo build

      - name: "Clone BlueCelluLab"
        run: git clone https://github.com/BlueBrain/BlueCelluLab.git

      - name: "Checkout BlueCelluLab commit"
        working-directory: BlueCelluLab
        run: |
          git checkout f12e6fe

      - name: "Test BlueCelluLab installation"
        working-directory: BlueCelluLab
        run: |
          while true; do
            rm -rf foo && \
            ../target/debug/uv venv --python 3.9 && \
            ../target/debug/uv pip install . --reinstall --cache-dir foo || break
          done

      - uses: actions/upload-artifact@v4
        with:
          name: foo-cache-dir
          path: foo
